---
- name: Generate Configuration for all routers
  gather_facts: no
  connection: local
  hosts: localhost
  vars:
    time: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') | random}}"
  roles:
    - { role: digest_lab_facts }
    - { role: generate_unl_file }
    # - { role: cleanup }